### ISSUE TITLE
Implementation of REST API layer

### ISSUE THREAD

**Issue by ksripathi** [vlead/lab-data-service#10]
This issue captures all the efforts required for implementing RESP APIs

Documentation can be found at https://github.com/vlead/lab-data-service/blob/develop/src/runtime/rest/api.org#the-rest-api

**Comment by ksripathi** [comment]
CRUD operation is done for all APIs related to Lab, Experiment, Section and Discipline

Documentation cab be found at : https://github.com/vlead/lab-data-service/blob/persistance-model/src/runtime/rest/api.org#the-rest-api

**Comment by sanchita-dixit** [comment]
CRUD operations for Lab, Experiment, Section, Discipline, Developer, Name, Email, Institute, Assets, Integration Status and Hosting Information is done. Entities - experiment, developer, Discipline, assets, hosting info and integration status have been integrated with lab entity.

Documentation could be found at : https://github.com/vlead/lab-data-service/blob/develop/src/runtime/rest/api.org#the-rest-api
