### ISSUE TITLE
populate lab phase data

### ISSUE THREAD

**Issue by ksripathi** [vlead/lab-data-service#107]
@madhavipuliraju 

Please document steps of how to populate the lab phase values. I observed that when we import sql dump file all phase values are empty this should be populated with all the values

**Comment by madhavipuliraju** [comment]
@ksripathi phase table is not populated yet. There is a provision in the database schema to update Phase information of a lab. Tables 'phase' and 'labs_phase' are empty as of now.

**Comment by sanchita-dixit** [comment]
@madhavipuliraju @ksripathi the above information is available at : [https://docs.google.com/spreadsheets/d/1m9nZzl_ehYNaTwX-92DI0GsgSkXRNPK2-Ay26fUmvWc/edit#gid=1217243506](https://docs.google.com/spreadsheets/d/1m9nZzl_ehYNaTwX-92DI0GsgSkXRNPK2-Ay26fUmvWc/edit#gid=1217243506)

**Comment by madhavipuliraju** [comment]
Implemented script to update Phase information of all Phase II labs.
Please refer to script: [link](https://github.com/vlead/lab-data-service/blob/master/src/deployment/index.org#program-to-update-phase-information-of-all-labs-which-are-on-phase-ii)

**Comment by madhavipuliraju** [comment]
Please refer to phase II labs info list with updated labid's : [Link](https://github.com/vlead/lab-specifications/blob/master/phase2-info.org)
URL: [lds-alpha.base4.vlabs.ac.in/labs](lds-alpha.base4.vlabs.ac.in/labs)
SQL Dump File with update phase II information : [http://files.vlabs.ac.in/lds/lds-v3.2.0-dump-2018-01-08.sql](http://files.vlabs.ac.in/lds/lds-v3.2.0-dump-2018-01-08.sql)
