### ISSUE TITLE
Testing the setup of Lab Data Service with Development Environment 

### ISSUE THREAD

**Issue by mrudhvika940** [vlead/lab-data-service#109]
Testing the setup of Lab Data Service with Development Environment

**Comment by sanchita-dixit** [comment]
I tested the lds setup in my machine in the development environment following the document successfully. 2 lines are added as a result in the final document regarding the installation of mysql and apache2 server which I faced as errors.

**Comment by mrudhvika940** [comment]
Closing this issue on behalf of @sanchita-dixit as there is no commit ID available for it as it was a testing task.
