### ISSUE TITLE
Dump latest lds database on file server for version v3.2.0

### ISSUE THREAD

**Issue by madhavipuliraju** [vlead/lab-data-service#112]
Dump latest lds database on file server for version v3.2.0

**Comment by kraghupathi** [comment]
Taken lds-v3.2.0 backup from [lds-alpha.base4.vlabs.ac.in](http://lds-alpha.base4.vlabs.ac.in/labs) and published in [files,vlabs.ac.in](http://files.vlabs.ac.in/lds/) server.
