### ISSUE TITLE
Collecting the list of phase-2 labs

### ISSUE THREAD

**Issue by mrudhvika940** [vlead/lab-data-service#114]
Collecting the list of id's of phase-2 labs

**Comment by mrudhvika940** [comment]
Visit this [file](https://github.com/vlead/lab-specifications/blob/master/phase2-info.org) for the phase II list of labs used for LDS database

**Comment by madhavipuliraju** [comment]
Reference : [https://github.com/vlead/lab-specifications/blob/master/phase2-info.org](https://github.com/vlead/lab-specifications/blob/master/phase2-info.org)
