### ISSUE TITLE
Update the new discipline IDs in the database

### ISSUE THREAD

**Issue by mrudhvika940** [vlead/lab-data-service#117]
With reference to the [discipline IDs ](https://github.com/vlead/lab-specifications/blob/master/discipline-to-id-mapping.org) in the lab-specifications repository update the new discipline IDs in the database.

**Comment by madhavipuliraju** [comment]
Reference: [http://lds-alpha.base4.vlabs.ac.in/disciplines](http://lds-alpha.base4.vlabs.ac.in/disciplines)
