### ISSUE TITLE
Review comments on lab data service release v0.1.0

### ISSUE THREAD

**Issue by madhavipuliraju** [vlead/lab-data-service#12]
Following are the review comments provided by Maruthi sir on 10/01/2017

Reference: https://github.com/vlead/lab-data-service/releases/tag/v0.1.0

Save exp spec data
1. sections": [ { "name": "Introduction" }, ...

I suggest sections": [ { "Introduction": "Introduction" }, ...

2. The example of the API is pointing to a local server.

3. Please have specific and elaborate error descriptions.

Get all experiments
1. If there are 1000 experiments, getting all will load the system, data and user experience. Is the API intended to get all experiments in a Lab? If so, the lab id should be specified as query parameter. Please review.

Please design pagination for heavy duty "GET" APIs. 

Get experiment by id, Update experiment by id , Delete experiment by id
I think it is a classic case. Though the HTTP allows to have such differentiation at the HTTP Verb level, the two APIs are different. So, please consider explicit APIs for put/post and get.

Save lab spec data
1. Suggest to have explicit API say, savelab etc. Usually GET is a default action. For example, /labs "gets all labs with pagination".

2. Usually, APIs are designed with some assumptions on Clients. I would say, every API return a TrackAPI id. Any client can get the status of APIs by querying the TrackAPI. Else, there is no trace of API calls and it is hard to trace back what happened in the system.

Get Lab bi ID, and update Lab by ID ...
Please refer to the earlier comments in the similar context.

Add Sections
1. I suggest to break the "functionality" into several APIs.
    Append Section 
    Insert After
    Insert Before
    Insert Head
    
    Update / Delete can be specific section.

2. Please differential bulk operations is any. Let such bulk operations are very explicit. 
    GetAllLabs, GetAllExperimetns/Lab etc.

General observation: 
The decision - add / update / delete a particular lab is embedded in HTTP body (payload). This may have performance issues.
Please design top level decisions using URL parameters. Parsing URL is cheaper than opening body all the time. 

Design Diagram:
I think using Webhook instantly may pose issues in maintaining the integrity of the system. I suggest a thin middle later to validate the GIT before pushing to lab-data-service. It may be a pass though now.

Process:
I think it is better to introduce a lab config data. It will host a global repo of the lab ids, experiment ids and utilities etc. 
Please specify the type of database for holding lab spec. Is it MySQL or Mongo or some Key-Value etc.

**Comment by ksripathi** [comment]
Attendees:
Thirumal, Sanchita, Balamma, Reena, Madhavi, Sripathi, Maruthi

Summary of LDS discussion on 3rd Jan 2017.

LDS system objectives:
Of many of the LDS objectives, three objectives were discussed. Please note that the conclusions are indicative and will help in better designs. So, please keep visiting the discussions till a better system design is thought of.

Objective #1: Make easy for Lab Developers use LDS
----------------------------------------------------------------------------
The very first step in the process is to finalise a Lab Spec / Experiment Spec through E-mails / Phone conversion among Lab Developers and VLEAD.

Spec (Lab + Experiment Spec) <== {Lab Developer <---------------> VLEAD}

The contents of the Spec such as IDs, names etc, is the reason for active engagement of Lab Developer, VLEAD; this MAY lead to delays, and more work on both the parties. 

If Lab Developers can use tools to generate Spec without much intervention of VLEAD, will ease the use of LDS services effectively and efficiently. Lab Developers can modify their work as needed and generate Spec. 

Ideally LDS should provide a DSL (Domain Specification Language) to generate Spec (Lab + Experiment Spec).

Suggestion: Study Sphinx, Docutils, reStructuredText and MAY derive patterns for LDS. 

Maruthi: I personally prefer reStructuredText and Sphinx till the point of Spec Generation. However, I leave it to the team to decide the best tools.

Objective #2: Make Spec and Content more relevant
----------------------------------------------------------------------------
There is a potential chance of either Spec or Content becomes stale. For example, a Lab Developer starts project with a version of Spec and Content (say V1). Any further changes involve further engagement of Lab Developers and VLEAD

Spec (Lab + Experiment Spec) V2 <== {Lab Developer <---------------> VLEAD} V2

This may not be a right UX and motivation for Lab Developers use LDS and publish their work on VLEAD.

So, to achieve this objective, a shift from LDS centric to Lab Developer centric is mooted. It means that VLEAD should focus TOOLs for Lab Developers. Lab Developers run the tools on the V2 and regenerate Spec (V2) and Content (V2) ... and so on. Lab Developer can PUSH the newer versions for approval (by VLEAD). This will ensure the relevance of Spec + Content and reduce bureaucracy of communication channels. 

Maruthi: I tend towards developing a DSL for LDS with proven tools to achieve the both the Objectives. 

Objective #3: Make a good choice of content addressable database(s)
---------------------------------------------------------------------------------------------------
Once a Lab Developer build a project of Spec + Content, then it is very important for the VLEAD to make to available over VLABS delivery mechanism.

{{Lab Developers} <---> {VLEAD}} => {Spec + Content} => VLABS (edX, portable...)

Given the current state of tools, especially databases, such as RIAK, the team should study such systems and make decision.

Suggestion: RIAK may well suit the LDS, however, please study, experiment and make a decision.

We also, discussed the current implementation of using simple files for content management. It will quickly pose challenges when dealing with scale of operations. A workaround is to learn the patters of SMTP Message Store and implement for LDS. However, it is very tedious. So, it is suggested to use RIAK or RIAK like databases.

**Comment by priya100raman** [comment]
Discussion of the review comments of LDS v0.1.0   on 11th Jan 2017

- Libsodium lib at the application level for cryptography (encryption of keys) and securing integrity of the data to be looked into. 
- Advantages of using this lib in place of HTTPS to be explored. 
- Zulu API service layer for authentication mechanism.
