### ISSUE TITLE
Populate the Lab Data Service database with the existing 80 lab specs

### ISSUE THREAD

**Issue by sanchita-dixit** [vlead/lab-data-service#23]

**Comment by travula** [comment]
@sanchita-dixit 

All 180 labs should be loaded to the lds database by 15th June

**Comment by sanchita-dixit** [comment]
The labspecs are pushed into the the LDS database except for 5-7 which are throwing errors while pushing to database and also 4 labspecs which couldn't be created due to URLs not working. Latest dump has been taken and pushed into files server on Base2. (165 labs) (http://files.vlabs.ac.in/lds/)

**Comment by sanchita-dixit** [comment]
All 173 labspecs have been pushed in the LDS database and a dump file is pushed into Base2 http://files.vlabs.ac.in/lds. This is the final labspec dump of the currently available labs with us.
