### ISSUE TITLE
data-model for lab-data-service

### ISSUE THREAD

**Issue by ksripathi** [vlead/lab-data-service#3]
This issue captures the documents related to data-model

**Comment by ksripathi** [comment]
Refer to doc at https://github.com/vlead/lab-data-service/blob/data-model/src/data-model/index.org#data-model-for-lab-data-service

**Comment by ksripathi** [comment]
Data-model is done for Lab, Experiment, Session, Disciplines, Developer and for Section is to be incorporated 

Data - Model documentation can be found at : https://github.com/vlead/lab-data-service/blob/persistance-model/src/data-model/index.org#data-model-for-lab-data-service

**Comment by sanchita-dixit** [comment]
Data Model is done for Lab, Experiment, Institute, Developer, Name, Email, Disciplines, Section, hosting Information, Integration Status and Asset.

Data - Model documentation can be found at : https://github.com/vlead/lab-data-service/blob/develop/src/data-model/index.org#data-model-for-lab-data-service
