### ISSUE TITLE
Implementation of Object Entitites

### ISSUE THREAD

**Issue by ksripathi** [vlead/lab-data-service#5]
This issue holds all the efforts required for Object entities implementation

**Comment by ksripathi** [comment]
Following are the list of entities to be implemented in object model 

1) Lab 

2) Experiment

3) Institute

4) Discipline

5) Developer

**Comment by ksripathi** [comment]
Implementation of entities in object model is done for following entities.

1) Lab            -   https://github.com/vlead/lab-data-service/blob/develop/src/runtime/objects/entities.org#lab

2) Experiment -  https://github.com/vlead/lab-data-service/blob/develop/src/runtime/objects/entities.org#experiment

3) Section       -  https://github.com/vlead/lab-data-service/blob/develop/src/runtime/objects/entities.org#section

4) Session      -   https://github.com/vlead/lab-data-service/blob/develop/src/runtime/objects/entities.org#session

5) Discipline   -   https://github.com/vlead/lab-data-service/blob/persistance-model/src/runtime/objects/entities.org#discipline

6) Institute - https://github.com/vlead/lab-data-service/blob/develop/src/runtime/objects/entities.org#institute

**Comment by sanchita-dixit** [comment]
Implementation of entities in object model is done for following entities.

   1. Lab - https://github.com/vlead/lab-data-service/blob/develop/src/runtime/objects/entities.org#lab

   2. Experiment - https://github.com/vlead/lab-data-service/blob/develop/src/runtime/objects/entities.org#experiment

   3. Section - https://github.com/vlead/lab-data-service/blob/develop/src/runtime/objects/entities.org#section

   4. Session - https://github.com/vlead/lab-data-service/blob/develop/src/runtime/objects/entities.org#session

   5. Discipline - https://github.com/vlead/lab-data-service/blob/persistance-model/src/runtime/objects/entities.org#discipline

   6. Institute - https://github.com/vlead/lab-data-service/blob/develop/src/runtime/objects/entities.org#institute

   7. Developer - https://github.com/vlead/lab-data-service/blob/develop/src/runtime/objects/entities.org#developer
   
  8. Name - https://github.com/vlead/lab-data-service/blob/develop/src/runtime/objects/entities.org#name

  9. Email - https://github.com/vlead/lab-data-service/blob/develop/src/runtime/objects/entities.org#email

  10. Asset - https://github.com/vlead/lab-data-service/blob/develop/src/runtime/objects/entities.org#asset

  11. Hosting Information - https://github.com/vlead/lab-data-service/blob/develop/src/runtime/objects/entities.org#hostinginfo

  12. Integration status - https://github.com/vlead/lab-data-service/blob/develop/src/runtime/objects/entities.org#integrationstatus
