### ISSUE TITLE
Fix issues in REST layer as per new lab and experiment specifications

### ISSUE THREAD

**Issue by sanchita-dixit** [vlead/lab-data-service#52]

**Comment by ksripathi** [comment]
Finalized specifications documented at https://github.com/vlead/lab-data-service/blob/develop/src/design/index.org#specification

A minor change in lab, experiment, discipline and institute specifications will effect all implementation and test cases in REST layer as well System Interface layer along with test cases

**Comment by ksripathi** [comment]
This issue got resolved and new implementation is as per finalized specifications documented at https://github.com/vlead/lab-data-service/blob/develop/src/design/index.org#specification
