### ISSUE TITLE
Refactor API documentation

### ISSUE THREAD

**Issue by sanchita-dixit** [vlead/lab-data-service#54]

**Comment by ksripathi** [comment]
implementation of specifications documented at https://github.com/vlead/lab-data-service/blob/develop/src/design/index.org#specification is completed

@mrudhvika940 
Could you please update the api documentation at https://github.com/vlead/lab-data-service/blob/develop/src/runtime/rest/api.org with respect to the REST requester plugin results.

please pull the develop branch code i have made all necessary changes to the code

**Comment by ksripathi** [comment]
updated documentation can be found at https://github.com/vlead/lab-data-service/blob/master/src/runtime/rest/api.org#the-rest-api
