### ISSUE TITLE
Implementation of Persistance Entities

### ISSUE THREAD

**Issue by ksripathi** [vlead/lab-data-service#6]

**Comment by ksripathi** [comment]
Implementation of entities in persistence model is done for following

1) Lab  - https://github.com/vlead/lab-data-service/blob/develop/src/runtime/persistence/entities.org#lab

2) Experiment  -  https://github.com/vlead/lab-data-service/blob/develop/src/runtime/persistence/entities.org#experiment

3) Section   - https://github.com/vlead/lab-data-service/blob/develop/src/runtime/persistence/entities.org#section

4) Discipline  -- https://github.com/vlead/lab-data-service/blob/persistance-model/src/runtime/persistence/entities.org#discipline

5) Institute - https://github.com/vlead/lab-data-service/blob/develop/src/runtime/persistence/entities.org#institute

**Comment by sanchita-dixit** [comment]
Implementation of entities in persistence model is done for following

1) Lab  - https://github.com/vlead/lab-data-service/blob/develop/src/runtime/persistence/entities.org#lab

2) Experiment  -  https://github.com/vlead/lab-data-service/blob/develop/src/runtime/persistence/entities.org#experiment

3) Section   - https://github.com/vlead/lab-data-service/blob/develop/src/runtime/persistence/entities.org#section

4) Discipline  -- https://github.com/vlead/lab-data-service/blob/persistance-model/src/runtime/persistence/entities.org#discipline

5) Institute - https://github.com/vlead/lab-data-service/blob/develop/src/runtime/persistence/entities.org#institute

 6) Session - https://github.com/vlead/lab-data-service/blob/develop/src/runtime/persistence/entities.org#session

 7) Developer - https://github.com/vlead/lab-data-service/blob/develop/src/runtime/persistence/entities.org#developer
   
 8) Name - https://github.com/vlead/lab-data-service/blob/develop/src/runtime/persistence/entities.org#name

 9) Email - https://github.com/vlead/lab-data-service/blob/develop/src/runtime/persistence/entities.org#email

 10) Asset - https://github.com/vlead/lab-data-service/blob/develop/src/runtime/persistence/entities.org#asset

 11) Hosting Information - https://github.com/vlead/lab-data-service/blob/develop/src/runtime/persistence/entities.org#hostinginfo

 12) Integration status - https://github.com/vlead/lab-data-service/blob/develop/src/runtime/persistence/entities.org#integrationstatus
