### ISSUE TITLE
API to generate the LDS specific lab specifications from the canonical specs (generic ones) 

### ISSUE THREAD

**Issue by sanchita-dixit** [vlead/lab-data-service#62]
We need to implement an API which takes the canonical lab specifications and generate the LDS specific lab specifications setting the other attributes (attributes which are present in the LDS specs but not in the canonical specs) as default.

**Comment by madhavipuliraju** [comment]
[Lab secifications](https://github.com/vlead/lab-specifications) release [lds-specs](https://github.com/vlead/lab-specifications/releases/tag/lds-specs) holds the canonical specs which are used for LDS.
