### ISSUE TITLE
Implementation of System Interface

### ISSUE THREAD

**Issue by ksripathi** [vlead/lab-data-service#7]
This issue captures all the efforts for implementing system interface layer.

**Comment by ksripathi** [comment]
Literate version of code can be found at https://github.com/vlead/lab-data-service/blob/develop/src/runtime/system/system-interface.org#system-interface-implementation-for-feedback-portal

**Comment by ksripathi** [comment]
All System Interface functions (CRUD) are implemented for Lab, Experiment, Section and Discipline entities 

Documentation can be found at https://github.com/vlead/lab-data-service/blob/develop/src/runtime/system/system-interface.org#the-systeminterface-class

**Comment by mrudhvika940** [comment]
All System Interface functions (CRUD) are implemented for Lab, Experiment, Section, Discipline, Institute, Developer, Name, Email, Hosting Information,Integration Status and Assets entities

Documentation can be found at https://github.com/vlead/lab-data-service/blob/develop/src/runtime/system/system-interface.org#the-systeminterface-class
