### ISSUE TITLE
Make Lab data service available in the staging and testing environment - base1 and base4

### ISSUE THREAD

**Issue by travula** [vlead/lab-data-service#74]
@madhavipuliraju 
@ksripathi 
The LDS should be available both on testing and staging environments.

**Comment by madhavipuliraju** [comment]
LDS was available for the release [v1.1.0]( https://github.com/vlead/lab-data-service/releases/tag/v1.1.0): 
Testing (Base 4): http://lds.base4.vlabs.ac.in/labs
Staging (Base1): http://lds.base1.vlabs.ac.in/labs

**Comment by madhavipuliraju** [comment]
LDS was available for release [v2.0.0](https://github.com/vlead/lab-data-service/releases/tag/v2.0.0):
Testing (Base 4): http://lds-migration.base4.vlabs.ac.in
Staging(Base 1): http://lds-migration.base1.vlabs.ac.in
