### ISSUE TITLE
Implementation of System Layer

### ISSUE THREAD

**Issue by ksripathi** [vlead/lab-data-service#8]
This issue captures all the efforts required for implementing system layer

**Comment by ksripathi** [comment]
Documentation of code snippet can be found at https://github.com/vlead/lab-data-service/blob/develop/src/runtime/system/system.org#system-implementation-for-feedback-portal

**Comment by ksripathi** [comment]
Implementation of CRUD operation is done for following entities

1) Lab   -  https://github.com/vlead/lab-data-service/blob/develop/src/runtime/system/system.org#operations

2) Experiment -- https://github.com/vlead/lab-data-service/blob/develop/src/runtime/system/system.org#addexperiment

3) Section  - https://github.com/vlead/lab-data-service/blob/develop/src/runtime/system/system.org#deletesection

4) Disciplines -  https://github.com/vlead/lab-data-service/blob/persistance-model/src/runtime/system/system.org#adddiscipline

5) Institute - https://github.com/vlead/lab-data-service/blob/develop/src/runtime/system/system.org#addinstitute

**Comment by mrudhvika940** [comment]
Implementation of CRUD operations is done for following entities
**A) Add operations**
1) Lab :  https://github.com/vlead/lab-data-service/blob/develop/src/runtime/system/system.org#operations
2) Experiment :  https://github.com/vlead/lab-data-service/blob/develop/src/runtime/system/system.org#addexperiment
3) Section :  https://github.com/vlead/lab-data-service/blob/develop/src/runtime/system/system.org#addsection
4) Disciplines :  https://github.com/vlead/lab-data-service/blob/develop/src/runtime/system/system.org#adddiscipline
5) Institute : https://github.com/vlead/lab-data-service/blob/develop/src/runtime/system/system.org#addinstitute
6) Hosting Information : https://github.com/vlead/lab-data-service/blob/develop/src/runtime/system/system.org#addhostinginfo
7) Name: https://github.com/vlead/lab-data-service/blob/develop/src/runtime/system/system.org#addname
8) Email : https://github.com/vlead/lab-data-service/blob/develop/src/runtime/system/system.org#addemail
9)Developer : https://github.com/vlead/lab-data-service/blob/develop/src/runtime/system/system.org#adddeveloper
10) Integration Status : https://github.com/vlead/lab-data-service/blob/develop/src/runtime/system/system.org#addintegrationstatus
**B) Update operations:**
1) Lab : https://github.com/vlead/lab-data-service/blob/develop/src/runtime/system/system.org#updatelab
2) Experiment : https://github.com/vlead/lab-data-service/blob/develop/src/runtime/system/system.org#updateexperiment
3)Section : https://github.com/vlead/lab-data-service/blob/develop/src/runtime/system/system.org#updatesection
4) Discipline : https://github.com/vlead/lab-data-service/blob/develop/src/runtime/system/system.org#updatediscipline
5) Institute : https://github.com/vlead/lab-data-service/blob/develop/src/runtime/system/system.org#updateinstitute
6) Hosting Information : https://github.com/vlead/lab-data-service/blob/develop/src/runtime/system/system.org#updatehostinginfo
7) Name : https://github.com/vlead/lab-data-service/blob/develop/src/runtime/system/system.org#updatename
8) Email : https://github.com/vlead/lab-data-service/blob/develop/src/runtime/system/system.org#updateemail
9) Developer : https://github.com/vlead/lab-data-service/blob/develop/src/runtime/system/system.org#updatedeveloper
10) Integration Status : https://github.com/vlead/lab-data-service/blob/develop/src/runtime/system/system.org#updateintegrationstatus
**C) Delete operations:**
1) Lab : https://github.com/vlead/lab-data-service/blob/develop/src/runtime/system/system.org#deletelab
2) Experiment : https://github.com/vlead/lab-data-service/blob/develop/src/runtime/system/system.org#deleteexperiment
3)Section : https://github.com/vlead/lab-data-service/blob/develop/src/runtime/system/system.org#deletesection
4) Discipline : https://github.com/vlead/lab-data-service/blob/develop/src/runtime/system/system.org#deletediscipline
5) Institute: https://github.com/vlead/lab-data-service/blob/develop/src/runtime/system/system.org#deleteinstitute
6) Hosting Information : https://github.com/vlead/lab-data-service/blob/develop/src/runtime/system/system.org#deletehostinginfo
7) Name : https://github.com/vlead/lab-data-service/blob/develop/src/runtime/system/system.org#deletename
8) Email : https://github.com/vlead/lab-data-service/blob/develop/src/runtime/system/system.org#deleteemail
9) Developer : https://github.com/vlead/lab-data-service/blob/develop/src/runtime/system/system.org#deletedeveloper
10) Integration Status : https://github.com/vlead/lab-data-service/blob/develop/src/runtime/system/system.org#deleteintegrationstatus
**D) Get operations:**
1) Lab : https://github.com/vlead/lab-data-service/blob/develop/src/runtime/system/system.org#getlab
2) Experiment : https://github.com/vlead/lab-data-service/blob/develop/src/runtime/system/system.org#getexperiment
3)Section : https://github.com/vlead/lab-data-service/blob/develop/src/runtime/system/system.org#getsection
4) Discipline : https://github.com/vlead/lab-data-service/blob/develop/src/runtime/system/system.org#getdiscipline
5) Institute : https://github.com/vlead/lab-data-service/blob/develop/src/runtime/system/system.org#getinstitute
6) Hosting Information : https://github.com/vlead/lab-data-service/blob/develop/src/runtime/system/system.org#gethostinginfo 
7) Name : https://github.com/vlead/lab-data-service/blob/develop/src/runtime/system/system.org#getname
8) Email : https://github.com/vlead/lab-data-service/blob/develop/src/runtime/system/system.org#getemail
9) Developer : https://github.com/vlead/lab-data-service/blob/develop/src/runtime/system/system.org#getdeveloper
10) Integration Status : https://github.com/vlead/lab-data-service/blob/develop/src/runtime/system/system.org#getintegrationstatus
