### ISSUE TITLE
Implementation of persistance delegates

### ISSUE THREAD

**Issue by ksripathi** [vlead/lab-data-service#9]
This issue captures all the efforts required for implementing persistance delegates.
documentation can be found at https://github.com/vlead/lab-data-service/blob/develop/src/runtime/system/persistence-delegate.org#persistence-delegate-for-the-system

**Comment by ksripathi** [comment]
All Delegates  functions (CRUD) are implemented for Lab, Experiment, Section and Discipline entities 

Documentation can be found at https://github.com/vlead/lab-data-service/blob/develop/src/runtime/system/persistence-delegate.org#persistence-delegate-for-the-system

**Comment by mrudhvika940** [comment]
All Delegate functions (CRUD) are implemented for Lab, Experiment, Section, Discipline, Institute, Name, Email, Hosting Information, Developer, Integration Status and Assets entities.

Documentation can be found at  https://github.com/vlead/lab-data-service/blob/develop/src/runtime/system/persistence-delegate.org#persistence-delegate-for-the-system
