### ISSUE TITLE
More labs to be captured.

### ISSUE THREAD

**Issue by travula** [vlead/lab-data-service#90]
refer [issue 13](https://github.com/vlead/vlabs-analytics-service/issues/13#issuecomment-328095328) of [vlabs-analytics-service](https://github.com/vlead/vlabs-analytics-service)

**Comment by madhavipuliraju** [comment]
@sanchita-dixit please update on this

**Comment by sanchita-dixit** [comment]
The status for this issue is captured [here](https://github.com/vlead/vlabs-landing-pages/issues/37).
