### ISSUE TITLE
create a new table 'Phase'  in the database

### ISSUE THREAD

**Issue by madhavipuliraju** [vlead/lab-data-service#91]
create a new field in the database.

set up a new field - phase - in the database, phase can have multiple values
1 denotes phase 1, 2 denotes phase 2, 3 phase 3 etc.

**Comment by travula** [comment]
@madhavipuliraju 

`phase` can be a new table

with attributes
phase_id (values 1, 2 3 ..)
and description.  phase_id is the key and can be null.
