### ISSUE TITLE
Some labs are not captured in lds database

### ISSUE THREAD

**Issue by madhavipuliraju** [vlead/lab-data-service#92]
There are some labs, that are not captured in the lds database.
Reference to list of lab_ids and their names : [link](https://github.com/vlead/lab-specifications/blob/master/lab-to-id-mapping.org#association-of-an-id-to-a-virtual-lab)

**Comment by travula** [comment]
refer [issue](https://github.com/vlead/vlabs-analytics-service/issues/13) on [vlabs-analytics-service](https://github.com/vlead/vlabs-analytics-service/)

**Comment by madhavipuliraju** [comment]
The status for this issue is captured [here](https://github.com/vlead/vlabs-landing-pages/issues/37).
