### ISSUE TITLE
Implementation of 'Pagination'

### ISSUE THREAD

**Issue by madhavipuliraju** [vlead/lab-data-service#99]
Implement 'Pagination' to break large record sets into smaller portions as pages.

**Comment by madhavipuliraju** [comment]
@obliviateandsurrender 
We would like to integrate Pagination in our next release.
Please send a pull request of your implementation.

**Comment by obliviateandsurrender** [comment]
@madhavipuliraju  To which branch should I send give a pull request to?

**Comment by madhavipuliraju** [comment]
@obliviateandsurrender 

Please send pull request to develop branch.

**Comment by madhavipuliraju** [comment]
Please Refer to:  
https://github.com/vlead/lab-data-service/blob/master/src/runtime/rest/api.org#pagination-support-for-get-request
